export type SessionState = {
  sessionKey: string | null;
  userId: number | null;
  nickname: string;
  createdAt: string | null;
  nicknameChangeCooldownUntil: number | null;
  lastNicknameUpdateServerTime: number | null;
  threadCreationCooldownUntil: number | null;
  lastThreadCreationServerTime: number | null;
  messageCreationCooldownUntil: number | null;
  lastMessageCreationServerTime: number | null;
  messagesCount: number;
  threadsCount: number;
  setUserId: (id: number | null) => void;
  setNickname: (nickname: string) => void;
  setNicknameChangeCooldownUntil: (timestamp: number | null) => void;
  setLastNicknameUpdateServerTime: (timestamp: number | null) => void;
  setThreadCreationCooldownUntil: (timestamp: number | null) => void;
  setLastThreadCreationServerTime: (timestamp: number | null) => void;
  setMessageCreationCooldownUntil: (timestamp: number | null) => void;
  setLastMessageCreationServerTime: (timestamp: number | null) => void;
  setMessagesCount: (count: number) => void;
  setThreadsCount: (count: number) => void;
  incrementMessagesCount: () => void;
  incrementThreadsCount: () => void;
  clear: () => void;
};
